### ISSUE TITLE
Multiple ng-form

### ISSUE THREAD

**Issue by feelitloveit** [GrumpyWizards/wizValidation#61]
When using "wiz-val-at-least-one" in multipe ng-form´s they get confused.
When you dynamicly add one all the other ng-forms go invalid!

**Comment by gregorypratt** [comment]
Are you using wiz-val-at-least-one="groupname" ?

**Comment by feelitloveit** [comment]
I am. Everything works great until I add or remove a form dynamicly.
I gave every generated input a dynamic name to solve name confilcts, but with no success.

**Comment by feelitloveit** [comment]
I found the problem.
1. You are doing a cleanup on destroy. There are happening destroy´s on my page. This is why another ng-form becomes invalid.
2. You are using the model as a name. In an ng-repeat these are not unique. (now I use the name atibute.)
